openapi: 3.0.0
info:
  title: Option Pricing and Sensitivities
  description: >-
    Option pricing using advanced models such as Heston, Extended Merton, and
    Extended CGMY.
  version: '1'
servers:
  - url: 'https://api.finside.org/realoptions'
    description: Production server
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-Key
security:
  - ApiKeyAuth: []
paths:
  '/v1/cgmy/calculator/{optionType}/{sensitivity}':
    post:
      summary: >-
        Calculator for computing option prices and sensitivities for a CGMY
        process
      description: >-
        Computes European option prices, implied volatilities, and sensitivities
        at every strike price for an asset that follows an extended CGMY process
      responses:
        '200':
          description: Option prices and sensitivites
          content:
            application/json:
              schema: &ref_0
                type: array
                items:
                  type: object
                  properties:
                    value:
                      type: number
                    at_point:
                      type: number
                    iv:
                      type: number
                  required:
                    - value
                    - at_point
                  additionalProperties: false
              example: &ref_1
                - value: 4
                  at_point: 50
                  iv: 0.5
                - value: 3
                  at_point: 60
                  iv: 0.6
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: &ref_2
                type: object
                properties:
                  err:
                    type: string
                required:
                  - err
                additionalProperties: false
      parameters:
        - name: optionType
          in: path
          required: true
          description: The type of option.
          schema:
            type: string
            enum:
              - call
              - put
        - name: sensitivity
          in: path
          required: true
          description: Prices or Greeks
          schema:
            type: string
            enum:
              - price
              - delta
              - gamma
              - theta
        - name: includeImpliedVolatility
          in: query
          description: >-
            Whether to include implied volatility in the results.  Defaults to
            'false'.  Only applicable for sensitivity='price'
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                asset:
                  type: number
                  example: 50
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    c:
                      type: number
                      example: 0.3
                    g:
                      type: number
                      example: 5
                    m:
                      type: number
                      example: 5
                    'y':
                      type: number
                      example: 1.2
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.9
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
                strikes:
                  type: array
                  items:
                    type: number
                  example:
                    - 50
              required:
                - num_u
                - rate
                - maturity
                - asset
                - cf_parameters
                - strikes
              additionalProperties: false
  '/v1/heston/calculator/{optionType}/{sensitivity}':
    post:
      summary: >-
        Calculator for computing option prices and sensitivities for a Heston
        model
      description: >-
        Computes European option prices, implied volatilities, and sensitivities
        at every strike price for an asset that follows a Heston process
      responses:
        '200':
          description: Option prices and sensitivites
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      parameters:
        - name: optionType
          in: path
          required: true
          description: The type of option.
          schema:
            type: string
            enum:
              - call
              - put
        - name: sensitivity
          in: path
          required: true
          description: Prices or Greeks
          schema:
            type: string
            enum:
              - price
              - delta
              - gamma
              - theta
        - name: includeImpliedVolatility
          in: query
          description: >-
            Whether to include implied volatility in the results.  Defaults to
            'false'.  Only applicable for sensitivity='price'
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                asset:
                  type: number
                  example: 50
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.25
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
                strikes:
                  type: array
                  items:
                    type: number
                  example:
                    - 50
              required:
                - num_u
                - rate
                - maturity
                - asset
                - cf_parameters
                - strikes
              additionalProperties: false
  '/v1/merton/calculator/{optionType}/{sensitivity}':
    post:
      summary: >-
        Calculator for computing option prices and sensitivities for a Merton
        model
      description: >-
        Computes European option prices, implied volatilities, and sensitivities
        at every strike price for an asset that follows an extended Merton
        process
      responses:
        '200':
          description: Option prices and sensitivites
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      parameters:
        - name: optionType
          in: path
          required: true
          description: The type of option.
          schema:
            type: string
            enum:
              - call
              - put
        - name: sensitivity
          in: path
          required: true
          description: Prices or Greeks
          schema:
            type: string
            enum:
              - price
              - delta
              - gamma
              - theta
        - name: includeImpliedVolatility
          in: query
          description: >-
            Whether to include implied volatility in the results.  Defaults to
            'false'.  Only applicable for sensitivity='price'
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                asset:
                  type: number
                  example: 50
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    mu_l:
                      type: number
                      example: -0.05
                    sig_l:
                      type: number
                      example: 0.2
                    lambda:
                      type: number
                      example: 1
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.9
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
                strikes:
                  type: array
                  items:
                    type: number
                  example:
                    - 50
              required:
                - num_u
                - rate
                - maturity
                - asset
                - cf_parameters
                - strikes
              additionalProperties: false
  /v1/cgmy/density:
    post:
      summary: Calculator for computing probability densities for CGMY process
      description: Computes probability density for an extended CGMY process
      responses:
        '200':
          description: Density
          content:
            application/json:
              schema: &ref_3
                type: array
                items:
                  type: object
                  properties:
                    value:
                      type: number
                    at_point:
                      type: number
                  required:
                    - value
                    - at_point
                  additionalProperties: false
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    c:
                      type: number
                      example: 0.3
                    g:
                      type: number
                      example: 5
                    m:
                      type: number
                      example: 5
                    'y':
                      type: number
                      example: 1.2
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.9
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
              required:
                - num_u
                - rate
                - maturity
                - cf_parameters
              additionalProperties: false
  /v1/heston/density:
    post:
      summary: Calculator for computing probability densities for Heston model
      description: Computes probability density for a Heston model
      responses:
        '200':
          description: Density
          content:
            application/json:
              schema: *ref_3
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.25
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
              required:
                - num_u
                - rate
                - maturity
                - cf_parameters
              additionalProperties: false
  /v1/merton/density:
    post:
      summary: Calculator for computing probability densities for Merton model
      description: Computes probability density for a Merton model
      responses:
        '200':
          description: Density
          content:
            application/json:
              schema: *ref_3
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    mu_l:
                      type: number
                      example: -0.05
                    sig_l:
                      type: number
                      example: 0.2
                    lambda:
                      type: number
                      example: 1
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.9
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
              required:
                - num_u
                - rate
                - maturity
                - cf_parameters
              additionalProperties: false
  /v1/cgmy/riskmetric:
    post:
      summary: Calculator for computing risk metrics for CGMY process
      description: Computes value at risk and expected shortfall for extended CGMY process
      responses:
        '200':
          description: Value at risk and expected shortfall
          content:
            application/json:
              schema: &ref_4
                type: object
                properties:
                  value_at_risk:
                    type: number
                  expected_shortfall:
                    type: number
                required:
                  - value_at_risk
                  - expected_shortfall
                additionalProperties: false
              example: &ref_5
                value_at_risk: 5
                expected_shortfall: 5
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    c:
                      type: number
                      example: 0.3
                    g:
                      type: number
                      example: 5
                    m:
                      type: number
                      example: 5
                    'y':
                      type: number
                      example: 1.2
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.9
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
                quantile:
                  type: number
                  example: 0.01
              required:
                - num_u
                - rate
                - maturity
                - cf_parameters
              additionalProperties: false
  /v1/heston/riskmetric:
    post:
      summary: Calculator for computing risk metrics for Heston model
      description: Computes value at risk and expected shortfall for a Heston model
      responses:
        '200':
          description: Value at risk and expected shortfall
          content:
            application/json:
              schema: *ref_4
              example: *ref_5
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.25
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
                quantile:
                  type: number
                  example: 0.01
              required:
                - num_u
                - rate
                - maturity
                - cf_parameters
                - quantile
              additionalProperties: false
  /v1/merton/riskmetric:
    post:
      summary: Calculator for computing risk metrics for Merton model
      description: >-
        Computes value at risk and expected shortfall for an extended Merton
        model
      responses:
        '200':
          description: Value at risk and expected shortfall
          content:
            application/json:
              schema: *ref_4
              example: *ref_5
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_u:
                  type: integer
                  example: 8
                rate:
                  type: number
                  example: 0.04
                maturity:
                  type: number
                  example: 0.5
                cf_parameters:
                  type: object
                  properties:
                    sigma:
                      type: number
                      example: 0.3
                    mu_l:
                      type: number
                      example: -0.05
                    sig_l:
                      type: number
                      example: 0.2
                    lambda:
                      type: number
                      example: 1
                    speed:
                      type: number
                      example: 0.2
                    v0:
                      type: number
                      example: 0.9
                    eta_v:
                      type: number
                      example: 0.2
                    rho:
                      type: number
                      example: -0.5
                  additionalProperties: false
                quantile:
                  type: number
                  example: 0.01
              required:
                - num_u
                - rate
                - maturity
                - cf_parameters
                - quantile
              additionalProperties: false
  /v1/heston/parameters/parameter_ranges:
    get:
      summary: Parameter Constraints
      description: >-
        Obtains the constraints that the parameters in the post requests are
        required to conform to for Heston.
      responses:
        '200':
          description: Constraints
          content:
            application/json:
              schema:
                type: object
                properties:
                  v0:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  speed:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  eta_v:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  sigma:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  rho:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                additionalProperties: false
              example:
                v0:
                  lower: 0
                  upper: 0.9
                  types: float
                speed:
                  lower: 0
                  upper: 2
                  types: float
                eta_v:
                  lower: 0
                  upper: 0.5
                  types: float
                sigma:
                  lower: 0
                  upper: 1
                  types: float
                rho:
                  lower: -1
                  upper: 1
                  types: float
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
  /v1/cgmy/parameters/parameter_ranges:
    get:
      summary: Parameter Constraints
      description: >-
        Obtains the constraints that the parameters in the post requests are
        required to conform to for CGMY.
      responses:
        '200':
          description: Constraints
          content:
            application/json:
              schema:
                type: object
                properties:
                  c:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  g:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  m:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  'y':
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  v0:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  speed:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  eta_v:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  sigma:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  rho:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                additionalProperties: false
              example:
                c:
                  lower: 0
                  upper: 10
                  type: float
                g:
                  lower: 0
                  upper: 20
                  type: float
                m:
                  lower: 0
                  upper: 20
                  type: float
                'y':
                  lower: -2
                  upper: 2
                  type: float
                v0:
                  lower: 0
                  upper: 2
                  type: float
                speed:
                  lower: 0
                  upper: 2
                  type: float
                eta_v:
                  lower: 0
                  upper: 0.5
                  type: float
                sigma:
                  lower: 0
                  upper: 1
                  type: float
                rho:
                  lower: -1
                  upper: 1
                  type: float
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
  /v1/merton/parameters/parameter_ranges:
    get:
      summary: Parameter Constraints
      description: >-
        Obtains the constraints that the parameters in the post requests are
        required to conform to for Merton.
      responses:
        '200':
          description: Constraints
          content:
            application/json:
              schema:
                type: object
                properties:
                  lambda:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  mu_l:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  sig_l:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  v0:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  speed:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  eta_v:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  sigma:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  rho:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                additionalProperties: false
              example:
                lambda:
                  lower: 0
                  upper: 4
                  types: float
                mu_l:
                  lower: 0
                  upper: 1
                  types: float
                sig_l:
                  lower: 0
                  upper: 0.6
                  types: float
                v0:
                  lower: 0
                  upper: 2
                  types: float
                speed:
                  lower: 0
                  upper: 2
                  types: float
                eta_v:
                  lower: 0
                  upper: 0.5
                  types: float
                sigma:
                  lower: 0
                  upper: 1
                  types: float
                rho:
                  lower: -1
                  upper: 1
                  types: float
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
  /v1/market/parameters/parameter_ranges:
    get:
      summary: Market Constraints
      description: Obtains the constraints that correspond with the market.
      responses:
        '200':
          description: Constraints
          content:
            application/json:
              schema:
                type: object
                properties:
                  rate:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  asset:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  maturity:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  num_u:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
                  quantile:
                    type: object
                    properties:
                      lower:
                        type: number
                      upper:
                        type: number
                      types:
                        type: string
                    required:
                      - lower
                      - upper
                      - types
                    additionalProperties: false
              example:
                asset:
                  lower: 0
                  upper: 1000000
                  types: float
                maturity:
                  lower: 0
                  upper: 1000000
                  types: float
                num_u:
                  lower: 5
                  upper: 10
                  types: int
                quantile:
                  lower: 0
                  upper: 1
                  types: float
                rate:
                  lower: 0
                  upper: 0.4
                  types: float
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
